# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0021_add_address_and_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PND', 'Sync Pending'), ('INP', 'Sync in Progress'), ('FL', 'Sync Failed'), ('FL', 'Sync Suceeded')], max_length=3)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_profile', to='profiles.Profile')),
            ],
        ),
    ]
